In [1]:
import numpy as np

In [2]:
y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.30, 0.7, 1, 0, 0.5])

In [11]:
def mean_absolute_error(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        # print(yt, yp)
        total_error += abs(yt - yp)
    print("total error: ", total_error)
    mae = total_error / len(y_true)
    print("MAE: ", mae)
    return mae

In [12]:
mean_absolute_error(y_true, y_predicted)

total error:  2.5
MAE:  0.5


0.5

In [13]:
y_predicted - y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [14]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [15]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [16]:
np.sum(np.abs(y_predicted - y_true))

2.5

In [17]:
# Log loss or Binary Cross Entropy

In [18]:
np.log([0])

/var/folders/gj/2w8tst8d3_b8_37zydzd259c0000gn/T/ipykernel_40160/262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [19]:
np.log([0.0000000000001])

array([-29.93360621])

In [20]:
epsilon = 1e-15

In [24]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [25]:
y_predicted_new = [min(i, 1 - epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [26]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [28]:
-np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

17.2696280766844

In [33]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1 - epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

In [34]:
log_loss(y_true, y_predicted)

17.2696280766844